name: RSS Feed Checker

on:
  schedule:
    - cron:  '*/15 * * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5.0.0
        with:
          go-version: '1.23'

      - name: Get dependencies
        run: go mod download

      - name: Run
        run: go run main.go
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_user_name: painhardcore # defaults to "github-actions[bot]"
          commit_user_email: painhardcore@gmail.com # defaults to "41898282+github-actions[bot]@users.noreply.github.com"
          commit_author: Andrey Yurchenkov <painhardcore@gmail.com> # defaults to author of the commit that triggered the run
          commit_message: Save the latest RSS feed items
